export const COMMAND_REQUEST = 'R'
export const COMMAND_RESPONSE_ERROR = 'E'
export const COMMAND_RESPONSE_FAILURE = 'F'
export const COMMAND_RESPONSE_SUCCESS = 'S'
export const SESSION_CREATE = 'C'
export const SESSION_DESTROY = 'D'
export const NOTIFICATION = 'N'
