export const CALL = 'R'
export const CALL_ERROR = 'E'
export const CALL_FAILURE = 'F'
export const CALL_SUCCESS = 'S'
export const SESSION_CREATE = 'C'
export const SESSION_DESTROY = 'D'
export const NOTIFICATION = 'N'
