export const COMMAND_REQUEST = 'R'
export const COMMAND_RESPONSE = 'E'
export const SESSION_CREATE = 'C'
export const SESSION_DESTROY = 'D'
export const TOPIC_PUBLISH = 'T'
export const TOPIC_SUBSCRIBED = 'S'
export const TOPIC_UNSUBSCRIBED = 'U'
