module.exports = {
  COMMAND_REQUEST: 'R',
  COMMAND_RESPONSE_ERROR: 'E',
  COMMAND_RESPONSE_FAILURE: 'F',
  COMMAND_RESPONSE_PARTIAL: 'P',
  COMMAND_RESPONSE_SUCCESS: 'S',
  SESSION_CREATE: 'C',
  SESSION_DESTROY: 'D',
  TOPIC_PUBLISH: 'T',
  TOPIC_SUBSCRIBED: 'L',
  TOPIC_UNSUBSCRIBED: 'U'
}
