module.exports = {
  COMMAND_REQUEST: 'R',
  COMMAND_RESPONSE_ERROR: 'E',
  COMMAND_RESPONSE_FAILURE: 'F',
  COMMAND_RESPONSE_SUCCESS: 'S',
  NOTIFICATION: 'N',
  SESSION_CREATE: 'C',
  SESSION_DESTROY: 'D'
}
